manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joshyeram                            # <--- add this
      url-base: https://github.com/joshyeram    # <--- and this
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: joshyeram
      revision: removeUSBpowercheck
      import: app/west.yml
    - name: prospector-zmk-module
      remote: joshyeram
      revision: support_nicenano                            # <---
  self:
    path: config